environment: development
chdir: /projects/jquery_expando_sample_app
address: 127.0.0.1
port: 5000
pid: /projects/jquery_expando_sample_app/tmp/thin.pid
rackup: /projects/jquery_expando_sample_app/config.ru
log: /projects/jquery_expando_sample_app/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 128
daemonize: true

